- index.json
The page to create an e-mail is https://m.kuku.lu/index.php
> Adding "svk.jp" to the list

- index.json
> Adding "ahk.jp" to the list

- index.json
Discovered this one from a user trying to sign up
> Adding another MintEmail subdomain

- index.json
ee2.pl is an alias of koszmail.pl
> Added ee2.pl

- component.json
- package.json
New version number in `package.json` and `component.json`.
Also, could you publish this version on npm please?
> Bump to 1.0.7

- index.json
> Added mail.wtf

- index.json
```
$ dig -t MX rootfest.net @8.8.8.8
; <<>> DiG 9.8.3-P1 <<>> -t MX rootfest.net @8.8.8.8
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 19167
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0
;rootfest.net.			IN	MX
rootfest.net.		299	IN	MX	20 lord.temp-mail.ru.
rootfest.net.		299	IN	MX	10 lord.temp-mail.org.
;; Query time: 73 msec
;; WHEN: Wed Oct 19 13:27:57 2016
;; MSG SIZE  rcvd: 97
```
> Add rootfest.net

- index.json
```
$ dig -t MX leeching.net @8.8.8.8
; <<>> DiG 9.8.3-P1 <<>> -t MX leeching.net @8.8.8.8
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 55491
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0
;leeching.net.			IN	MX
leeching.net.		20528	IN	MX	10 angel.temp-mail.org.
leeching.net.		20528	IN	MX	20 angel.temp-mail.ru.
;; Query time: 39 msec
;; WHEN: Tue Oct 25 12:11:07 2016
;; MSG SIZE  rcvd: 99
```
> Add leeching.net

- index.json
This is the current disposable domain for tempail.com
```
$ dig yroid.com @8.8.8.8
; <<>> DiG 9.8.3-P1 <<>> yroid.com @8.8.8.8
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 49125
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;yroid.com.			IN	A
yroid.com.		14399	IN	A	168.235.95.192
;; Query time: 99 msec
;; WHEN: Tue Oct 25 15:47:19 2016
;; MSG SIZE  rcvd: 43
```
```
$ dig tempail.com  @8.8.8.8
; <<>> DiG 9.8.3-P1 <<>> tempail.com @8.8.8.8
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 19956
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;tempail.com.			IN	A
;; ANSWER …
```
> Add yroid.com

- index.json
```
$ dig -t MX itsme.edu.pl @8.8.8.8
; <<>> DiG 9.8.3-P1 <<>> -t MX itsme.edu.pl @8.8.8.8
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 21631
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 0
;itsme.edu.pl.			IN	MX
itsme.edu.pl.		3599	IN	MX	10 mx2.mytemp.email.
itsme.edu.pl.		3599	IN	MX	10 mx1.mytemp.email.
itsme.edu.pl.		3599	IN	MX	10 mx3.mytemp.email.
;; Query time: 286 msec
;; WHEN: Mon Nov  7 10:11:20 2016
;; MSG SIZE  rcvd: 102
```
> Add itsme.edu.pl

- index.json
```
$ dig -t MX mail.godut.com @8.8.8.8
; <<>> DiG 9.8.3-P1 <<>> -t MX mail.godut.com @8.8.8.8
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 5087
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0
;mail.godut.com.			IN	MX
;; AUTHORITY SECTION:
godut.com.		179	IN	SOA	ns1.tempail.com. root.godut.com. 2016102305 7200 3600 1209600 180
;; Query time: 88 msec
;; WHEN: Mon Nov  7 10:12:25 2016
;; MSG SIZE  rcvd: 85
```
> Add godut.com

- Readme.md
- package.json
Advantages
- Doesn't require mocha to be installed globally.
- Allows for future CI intergration.
> [Test] Add npm script

- index.json
> Add trashmail.io

- index.json
> Added nbox.notif.me

- index.json
This domain offers 15 minutes temporary email
> Added domain dqnwara.com

- index.json
See here: https://translate.google.it/translate?sl=ja&tl=en&u=http%3A%2F%2Fsute.jp%2F
> Added sute.jp domain

- index.json
> 10minut.com.pl

- index.json
adding a disposable email noticed in our user base.
> added 20minutemail.it

- index.json
> Added new disposable

- wildcard.json
b7ffv.anonbox.net seen, shortening as anonbox.net in this file
> Add new subdomain

- index.json
Added domain provided by https://www.tempmailaddress.com/window/id/1
> Adding 0hiolce.com

- index.json
> Add you-spam.com

- index.json
> @kpooa.com

- index.json
> Added emailna.life

- index.json
> adding mailbox52.ga and mailbox87.de

- index.json
lm0k.com found on minuteinbox.com
> added lm0k.com

- index.json
> adding lron0re.com

- index.json
> adding lam0k.com from https://www.minuteinbox.com/

- index.json
> adding uapproves.com from emailondeck

- index.json
> added dress9x.com, found on emailondeck.com

- index.json
> adding lcelandic.com from tempmailaddress.com

- index.json
> adding jqweblogs.com from emailondeck

- index.json
> adding asdf.pl found at asdf.pl

- index.json
> adding tempmail.top

- index.json
Adds dtools.info after receiving a large amount of abuse.
Source: http://utilities-online.info/email/
> Adds dtools.info

- index.json
(thanks to chrome translate) ![image](https://user-images.githubusercontent.com/3769077/46215652-e8a53d80-c30b-11e8-9dd7-d12b434e5009.png)
> docmail.cz

- index.json
> kdublinstj.com

- index.json
> lnvoke.net

- index.json
> adding two0aks.com

- index.json
> adding tcnmistakes.com

- index.json
Greetings from www.block-disposable-email.com
> ebbob.com from 10minutemail.net

- index.json
> polishxwyb.com

- index.json
> wkschemesx.com

- index.json
> 0ne0ut.com

- index.json
Greetings from www.block-disposable-email.com ;-)
> iencm.com from 10minutemail.net

- index.json
> mailgen.biz

- index.json
> new domain

- index.json
> adding domain doublemail.de

- index.json
> Add my365.tw

- index.json
had asked about this earlier and was told it was fine, but found it going directly to their site
> email on deck :(

- index.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ivolo/disposable-email-domains/522)
> code-mail.com

- index.json
also one that refreshes less often, but commonly missed
> minuteinbox

- index.json
there may be more, but these are the only ones i saw
> mailshiv.com

- index.json
The Telegram Bot Fake Mail added a new domain
> Fake Mail Telegram Bot Domain

- index.json
From here:
https://www.mohmal.com/pt/inbox
> Add emailcu.icu
