index.json
[Translation of the page](https://translate.google.com/translate?hl=en&sl=zh-CN&u=http://24mail.chacuo.net/) that provides the disposable email.
=> Adding chacuo domains

index.json
Looks like `hostcalls.com` is just a front for `temp-mail.ru`
```
$ dig -t MX hostcalls.com @8.8.8.8
; <<>> DiG 9.8.3-P1 <<>> -t MX hostcalls.com @8.8.8.8
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 65095
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0
;hostcalls.com.			IN	MX
hostcalls.com.		299	IN	MX	20 lord.temp-mail.ru.
hostcalls.com.		299	IN	MX	10 lord.temp-mail.org.
;; Query time: 56 msec
;; WHEN: Tue Oct 11 12:41:21 2016
;; MSG SIZE  rcvd: 98
```
=> Adding hostcalls.com

index.json
Seeing a large number of fake users making use of md5hashing.net. Seems to stem from [this service](https://md5hashing.net/anonymous/email).
=> Adds md5hashing.net

index.json
We have encountered a number of abusers making use of ibsats.com - a quick google search shows it as belonging to www.throwawaymail.com.
<3 your work!
=> Adds ibsats.com (www.throwawaymail.com)

wildcard.json
It tells you can use any symbols before domain (like something@likethis.emlpro.com), so we should add their domains to wildcards
=> Add all dropmail.me wildcard domains

index.json
[We](https://zeit.co) are seeing malicious traffic coming from such domains.
[zebra.email](http://zebra.email) and [ziyap.com](http://ziyap.com) clearly offer disposable emails. 9toplay.com's website is not being served at the moment, but [it can be found in other blacklists](https://github.com/phillipp/spam_email/blob/master/lib/spam_email/blacklist.rb#L138).
=> Add 9toplay.com, zebra.email and ziyap.com

index.json
This seems like a "free email provider" (albeit in chinese) rather than a "disposable email provider".
It was originally added in commit 8def12 which imported martenson/disposable-email-domains. That in turn added it in martenson/disposable-email-domains@ce7d3f.
=> Remove sohu.com

index.json
The domain loanins.org is used as a DEA to create fake Wordpress accounts. Easy to check just googling.
=> Add loanins.org to the list

index.json
This is a standard free email provider, not a disposable one. As such it has been added to https://gitlab.com/synappio/free-email-domains
=> Remove c2.hu

index.json
=> adding drivesotp7.com

index.json
yes, that is tempail.com and not tempmail.com
=> adding ezehe.com from tempail.com

index.json
google search shows trashmail in the header as well.
=> phaantm.de

index.json
From `freeinbox.email` domain (a French disposable domain)
=> Add freeinbox.email

index.json
In use at [https://www.throwawaymail.com](https://www.throwawaymail.com)
=> Add mywrld.top

index.json
this provider seems to be pretty commonly missed as well
=> tempmailaddress

index.json
Not really meant to be a disposable, but is being used on our site as a disposable.
=> new domain

index.json
supposed to be used for testing emails, which allows you to create a dummy mailbox and then view the mailbox. so of course people are using it for disposables.
=> putsbox.com

index.json
* The domain `aver.com` was originally added to the list in 2014 (https://github.com/ivolo/disposable-email-domains/pull/14)
* The domain ownership has since changed and the domain is used by a [reputable video conferencing company](https://aver.com)
* [WhoIs Information](https://who.is/whois/aver.com)
=> Remove aver.com from list

index.json
According to https://fakecheck.email/mail2paste.com and, well, the _domain name itself_ this is a disposable email domain.
=> add mail2paste.com as disposable domain

index.json
I've been dealing with blocked and bouncing email for the past year. I'm not able to signup for many services. After much searching, I discovered my personal domain is incorrectly listed as disposable. It is unclear how it landed on this list. This is a mistake. My mail is hosted at namecheap. Look at the MX records yourself (`dig mx ruffrey.com`).
I only have one single email address under this domain. I have had this email address for 10 years.
=> Removes a personal, non-disposable domain

wildcard.json
Fix #935 
Apparently wildcard is too strict for this one. Compare e.g. https://check-mail.org/domain/edu.pl/ vs https://check-mail.org/domain/pw.edu.pl/
=> Remove edu.pl from the wildcard list

index.json
The localhomepro.com domain is now valid, and points to Google mail domains, [as can be seen here](https://mxtoolbox.com/SuperTool.aspx?action=mx%3alocalhomepro.com&run=toolpage).
=> Removed localhomepro.com from list

index.json
Ubicloud.com is our startup's domain and has its SPF, DKIM, and DMARC records properly configured.
Every time we need to sign up to a SaaS service such as Slack, Heroku, levels.fyi, etc., we need to contact their dev team. This pull request fixes the source blacklist instead.
=> Update emails.txt to remove ubicloud.com
